
;==============================================================================
; AMIGA GAME ENGINE
; bigfont.asm  -  Proportional "hero text" blit routines (Michroma font)
;==============================================================================
;
; Large placard-style text (e.g. the PURGE flash effect) — a different system
; from char_bltroutines.asm's 8x8 monospace font. Michroma is a wide, strongly
; non-monospace face (a bold 'W' is ~6x an 'I'), so glyphs here are
; proportional: each stores its own byte width (MichromaWidths) and the blit
; advances by that glyph's own width rather than a fixed column. Data tables
; (MichromaFont/Offsets/Widths/CharMap, MICHROMA_H/MICHROMA_GLYPHS) come from
; michroma_font_data.asm, generated by assets/font/generate_michroma_font.py —
; see that script's docstring for the rasterisation/sizing rationale (336x200
; canvas, 4x-supersampled Michroma at 56pt, byte-rounded proportional widths;
; the rounding remainder doubles as inter-letter spacing).
;
; All routines share char_bltroutines.asm's screen-geometry assumption:
; LOADING_WIDTH_BYTE (42) wide bitplanes, LOADING_ROW_BYTES (210) stride —
; true of every screen in this game (loading, title, instructions,
; level-complete, game). Every glyph is written to all 5 bitplanes (colour
; index 31 = white, same convention as CHAR_BLTOneChar).
;
; Routines defined here:
;   MichromaGlyphLookup   - ASCII char -> glyph bitmap ptr (a0) + width (d3.w)
;   MichromaStringWidth   - null-terminated string -> total width in bytes
;   MichromaCenterX       - total width (d0.w) -> centred start byte-column
;   MichromaBLTChar       - blit/erase one glyph, all 5 planes (white)
;   MichromaBLTString     - blit/erase a null-terminated string
;   MichromaFlashInit     - arm the flash timer for a fixed string+position
;   MichromaFlashTick     - call once per frame; toggles draw/erase on period
;   MichromaFlashStop     - disarm the flash (erasing first if visible)
;==============================================================================

MICHROMA_FLASH_PERIOD = 25      ; PAL frames between toggles (~0.5s @ 50Hz);
                                 ; armed through ScalePALFrames at init time


;==============================================================================
; MichromaGlyphLookup  -  Resolve an ASCII character to its glyph data
;
; On entry: d2.b = ASCII character.
; On return: a0 = glyph bitmap pointer (MICHROMA_H rows, d3.w bytes/row);
;            d3.w = byte width (bytes per row) of this glyph.
; Destroys: d0/d1.
;==============================================================================

MichromaGlyphLookup:
    moveq      #0,d0
    move.b     d2,d0
    and.w      #$FF,d0
    lea        MichromaCharMap,a0
    move.b     0(a0,d0.w),d0        ; d0 = glyph index (0..MICHROMA_GLYPHS-1)
    and.w      #$FF,d0
    add.w      d0,d0                ; word-table index

    lea        MichromaOffsets,a0
    moveq      #0,d1
    move.w     0(a0,d0.w),d1        ; d1 = byte offset into MichromaFont (zero-
                                     ; extended: move.w only sets the low word,
                                     ; and d1 is add.l'd into a0 below as a full
                                     ; longword - stale upper-word garbage here
                                     ; produced a wild glyph pointer, i.e. static)

    lea        MichromaWidths,a0
    move.w     0(a0,d0.w),d3        ; d3 = byte width (bytes/row)

    lea        MichromaFont,a0
    add.l      d1,a0                ; a0 -> this glyph's bitmap data
    rts


;==============================================================================
; MichromaStringWidth  -  Total byte width of a null-terminated string
;
; On entry: a0 = null-terminated ASCII string.
; On return: d0.w = total width in bytes (sum of each glyph's width).
; Destroys: nothing else - a0/a1/d1-d4 are all saved/restored internally
; (PUSHM/POPM); d0 is excluded from that list so it can carry the result out.
; Callers must not rely on this for any OTHER register: MichromaGlyphLookup
; (called per character) still destroys d0/d1/d3 - see its header - it's just
; that this routine's own PUSHM/POPM shields its own caller from that.
;==============================================================================

MichromaStringWidth:
    PUSHM      d1-d4/a0/a1
    move.l     a0,a1
    moveq      #0,d4
.loop
    move.b     (a1)+,d2
    beq        .done
    bsr        MichromaGlyphLookup
    add.w      d3,d4
    bra        .loop
.done
    move.w     d4,d0                ; stash result before POPM restores d1-d4
    POPM       d1-d4/a0/a1
    rts


;==============================================================================
; MichromaCenterX  -  Centred start byte-column for a given total width
;
; On entry: d0.w = total width in bytes.
; On return: d0.w = start byte-column within a LOADING_WIDTH_BYTE-wide row.
; Destroys: d1.
;==============================================================================

MichromaCenterX:
    move.w     #LOADING_WIDTH_BYTE,d1
    sub.w      d0,d1
    asr.w      #1,d1
    move.w     d1,d0
    rts


;==============================================================================
; MichromaBLTChar  -  Blit or erase one glyph, all 5 planes (white)
;
; On entry: d2.b = ASCII character; a1 = screen byte address (plane 0, top row
;           of this glyph's cell); d7.b = 0 draws (white), non-zero erases
;           (clears the same footprint — used for the flash "off" state).
; On return: a1 advanced by this glyph's byte width (next char's column).
; Destroys: d0/d1/d3-d6, a0/a2/a3.
;
; Note: plane 4's row offset (CHAR_PLANE4 = 168) doesn't fit the 68000's 8-bit
; displacement limit for register-indexed addressing (d8(An,Xn) - unlike
; char_bltroutines.asm's MAKE_GLYPH_BODY, this routine indexes by column
; (d5.w) as well as by plane, so CHAR_PLANE4(a2,d5.w) would need a 16-bit
; displacement, 020+ only). a3 is pre-offset to plane 4's row start each row
; via LEA (plain d16(An), no index - fits fine), then indexed with 0 displacement.
;==============================================================================

MichromaBLTChar:
    PUSHM      d0/d1/d3-d6/a0/a2-a3
    bsr        MichromaGlyphLookup      ; a0 = glyph data, d3.w = byte width

    move.l     a1,a2
    moveq      #MICHROMA_H-1,d4
    tst.b      d7
    bne.s      .erase_rows

.draw_rows
    lea        CHAR_PLANE4(a2),a3
    moveq      #0,d5
.draw_col
    move.b     (a0)+,d6
    move.b     d6,0(a2,d5.w)
    move.b     d6,CHAR_PLANE1(a2,d5.w)
    move.b     d6,CHAR_PLANE2(a2,d5.w)
    move.b     d6,CHAR_PLANE3(a2,d5.w)
    move.b     d6,0(a3,d5.w)
    addq.w     #1,d5
    cmp.w      d3,d5
    blt.s      .draw_col
    add.w      #LOADING_ROW_BYTES,a2
    dbra       d4,.draw_rows
    bra.s      .advance

.erase_rows
    lea        CHAR_PLANE4(a2),a3
    moveq      #0,d5
.erase_col
    clr.b      0(a2,d5.w)
    clr.b      CHAR_PLANE1(a2,d5.w)
    clr.b      CHAR_PLANE2(a2,d5.w)
    clr.b      CHAR_PLANE3(a2,d5.w)
    clr.b      0(a3,d5.w)
    addq.w     #1,d5
    cmp.w      d3,d5
    blt.s      .erase_col
    add.w      #LOADING_ROW_BYTES,a2
    dbra       d4,.erase_rows

.advance
    add.w      d3,a1
    POPM       d0/d1/d3-d6/a0/a2-a3
    rts


;==============================================================================
; MichromaBLTString  -  Blit or erase a null-terminated string
;
; On entry: a0 = null-terminated ASCII string; a1 = screen address (plane 0)
;           of the first glyph's cell; d7.b = 0 draws / non-zero erases.
; On return: a1 advanced past the last character.
; Destroys: d0-d6, a0.
;==============================================================================

MichromaBLTString:
    PUSHM      d2/a0
.loop
    move.b     (a0)+,d2
    beq        .done
    bsr        MichromaBLTChar
    bra        .loop
.done
    POPM       d2/a0
    rts


;==============================================================================
; MichromaFlashInit  -  Arm a flashing, horizontally centred string
;
; On entry: a0 = null-terminated ASCII string (must stay valid while armed —
;           callers should pass a static string, not stack/scratch memory);
;           d1.w = screen row (0-based); a2 = screen buffer base address
;           (e.g. DisplayScreen). Draws the string immediately (starts
;           visible) and arms the timer for MichromaFlashTick.
; Destroys: d0/d1/d3-d6, a0-a2.
;==============================================================================

MichromaFlashInit:
    move.l     a0,PurgeFlashString(a5)

    ; Consume the row parameter (d1) into the row's base address BEFORE
    ; calling MichromaCenterX, which destroys d1 as scratch (see its header) -
    ; doing this in the other order silently drops the caller's row number.
    mulu       #LOADING_ROW_BYTES,d1
    move.l     a2,a1
    add.l      d1,a1                    ; a1 = row's base address

    bsr        MichromaStringWidth      ; d0.w = total width (a0/a1 preserved)
    bsr        MichromaCenterX          ; d0.w = start byte column

    add.w      d0,a1                    ; a1 = final screen address
    move.l     a1,PurgeFlashAddr(a5)

    move.w     #MICHROMA_FLASH_PERIOD,d0
    bsr        ScalePALFrames
    move.w     d0,PurgeFlashPeriod(a5)
    move.w     d0,PurgeFlashTimer(a5)
    move.w     #1,PurgeFlashOn(a5)

    move.l     PurgeFlashString(a5),a0
    move.l     PurgeFlashAddr(a5),a1
    moveq      #0,d7                    ; mode = draw
    bsr        MichromaBLTString
    rts


;==============================================================================
; MichromaFlashTick  -  Call once per frame; toggles the armed string
;
; No-op if nothing is armed (PurgeFlashString = 0).
; Destroys: d0-d6, a0-a2 (only when a toggle fires this frame).
;==============================================================================

MichromaFlashTick:
    tst.l      PurgeFlashString(a5)
    beq.s      .none
    subq.w     #1,PurgeFlashTimer(a5)
    bgt.s      .none

    move.w     PurgeFlashPeriod(a5),PurgeFlashTimer(a5)
    move.w     PurgeFlashOn(a5),d0
    eor.w      #1,d0
    move.w     d0,PurgeFlashOn(a5)      ; d0 = new on/off state
    move.w     d0,d7
    eor.w      #1,d7                    ; mode: on(1)->draw(0), off(0)->erase(1)

    move.l     PurgeFlashString(a5),a0
    move.l     PurgeFlashAddr(a5),a1
    bsr        MichromaBLTString
.none
    rts


;==============================================================================
; MichromaFlashStop  -  Disarm the flash (erasing the string first if visible)
;==============================================================================

MichromaFlashStop:
    tst.l      PurgeFlashString(a5)
    beq.s      .done
    tst.w      PurgeFlashOn(a5)
    beq.s      .clear
    move.l     PurgeFlashString(a5),a0
    move.l     PurgeFlashAddr(a5),a1
    moveq      #1,d7                    ; mode = erase
    bsr        MichromaBLTString
.clear
    clr.l      PurgeFlashString(a5)
.done
    rts
