
;==============================================================================
; AMIGA GAME ENGINE
; char_bltroutines.asm  -  Character blit routines for 336-wide (42-byte plane) screens
;==============================================================================
;
; These routines operate on any screen that uses LOADING_WIDTH_BYTE (42) wide
; bitplanes and a row stride of LOADING_ROW_BYTES (210 = SCREEN_STRIDE).  That
; covers all screens: loading, title, instructions, level-complete, and game.
;
; All glyph routines share one implementation, generated by the
; MAKE_GLYPH_BODY macro below with a per-plane write/clear selection.  The
; resulting colour is the palette index whose bit pattern matches the planes
; that receive the glyph (bit 0 = plane 0 ... bit 4 = plane 4).
;
; Routines defined here:
;   CHAR_BLTString        - null-terminated ASCII string (white)
;   CHAR_BLTNum3          - 3-digit decimal word value (white)
;   CHAR_BLTOneChar       - single glyph, all 5 planes (white, colour 31)
;   CHAR_DrawBlockChar    - solid fill byte to planes 3+4 (block cursor)
;   CHAR_BLTGreenChar     - single glyph, planes 3+4  (green,  colour 24)
;   CHAR_BLTYellowChar    - single glyph, planes 1+3+4 (yellow, colour 26)
;   CHAR_BLTRedChar       - single glyph, planes 2+3+4 (red,    colour 28)
;   CHAR_BLTStringGreen   - null-terminated string (green)
;   CHAR_BLTStringYellow  - null-terminated string (yellow)
;   CHAR_BLTStringRed     - null-terminated string (red)
;==============================================================================

; Byte offset of plane N within one interleaved screen row
CHAR_PLANE1         = LOADING_WIDTH_BYTE
CHAR_PLANE2         = LOADING_WIDTH_BYTE*2
CHAR_PLANE3         = LOADING_WIDTH_BYTE*3
CHAR_PLANE4         = LOADING_WIDTH_BYTE*4


;==============================================================================
; MAKE_GLYPH_BODY  -  Generate one 8x8 glyph blit routine body
;
; Arguments \1..\5 select what each of the five planes receives:
;   1 = the glyph byte, 0 = cleared to zero.
; Argument \6 selects the bold behaviour:
;   0 = bold smear only when FontBold(a5) is set (white text variant)
;   1 = always bold (coloured text variants — matches original behaviour)
;
; Generated routine contract (same for every variant):
;   On entry: d2.b = ASCII character (32-127); a1 = screen byte address (plane 0).
;   On return: a1 advanced by 1 byte (next character column).
;   Preserves everything else (PUSHM/POPM).
;==============================================================================

MAKE_GLYPH_BODY    MACRO
                   PUSHM       d3-d6/a0/a2

                   moveq       #0,d3
                   move.b      d2,d3
                   sub.b       #' ',d3
                   bmi         .\@skip
                   cmp.b       #96,d3
                   bge         .\@skip
                   lsl.w       #3,d3               ; d3 = (char - ' ') * 8
                   lea         ActiveFont,a0
                   add.w       d3,a0               ; a0 -> 8 glyph bytes

                   IFEQ        \6
                   tst.w       FontBold(a5)
                   sne         d5                  ; d5 = $FF if bold, $00 if normal
                   ENDC

                   move.l      a1,a2
                   moveq       #7,d4
.\@row
                   move.b      (a0)+,d3
                   move.b      d3,d6
                   lsr.b       #1,d6
                   IFEQ        \6
                   and.b       d5,d6               ; smear only when FontBold set
                   ENDC
                   or.b        d6,d3               ; bold smear: d3 |= (d3 >> 1)

                   IFNE        \1
                   move.b      d3,0(a2)            ; plane 0
                   ELSE
                   clr.b       0(a2)
                   ENDC
                   IFNE        \2
                   move.b      d3,CHAR_PLANE1(a2)  ; plane 1
                   ELSE
                   clr.b       CHAR_PLANE1(a2)
                   ENDC
                   IFNE        \3
                   move.b      d3,CHAR_PLANE2(a2)  ; plane 2
                   ELSE
                   clr.b       CHAR_PLANE2(a2)
                   ENDC
                   IFNE        \4
                   move.b      d3,CHAR_PLANE3(a2)  ; plane 3
                   ELSE
                   clr.b       CHAR_PLANE3(a2)
                   ENDC
                   IFNE        \5
                   move.b      d3,CHAR_PLANE4(a2)  ; plane 4
                   ELSE
                   clr.b       CHAR_PLANE4(a2)
                   ENDC

                   add.w       #LOADING_ROW_BYTES,a2
                   dbra        d4,.\@row

.\@skip
                   addq.l      #1,a1

                   POPM        d3-d6/a0/a2
                   rts
                   ENDM


;==============================================================================
; Single-glyph routines (generated from MAKE_GLYPH_BODY)
;
;   CHAR_BLTOneChar    all 5 planes  -> colour 31 (white); FontBold-controlled
;   CHAR_BLTGreenChar  planes 3+4    -> colour 24 (green);  always bold
;   CHAR_BLTYellowChar planes 1+3+4  -> colour 26 (yellow); always bold
;   CHAR_BLTRedChar    planes 2+3+4  -> colour 28 (red);    always bold
;==============================================================================

CHAR_BLTOneChar:
                   MAKE_GLYPH_BODY 1,1,1,1,1,0

CHAR_BLTGreenChar:
                   MAKE_GLYPH_BODY 0,0,0,1,1,1

CHAR_BLTYellowChar:
                   MAKE_GLYPH_BODY 0,1,0,1,1,1

CHAR_BLTRedChar:
                   MAKE_GLYPH_BODY 0,0,1,1,1,1

; CHAR_BLTHudChar — planes 0+1 (colour value 3), always bold.  Used for the
; level-transition banner (LevelBannerShow, levelutils.asm): on the game
; screen's palette (cpPal, colours 16-31 from SpritePal) this index reads
; pure white regardless of which tileset/chapter is active, since SpritePal
; is shared across all five tilesets — see tools/draw_players.py's PAL table.
CHAR_BLTHudChar:
                   MAKE_GLYPH_BODY 1,1,0,0,0,1


;==============================================================================
; CHAR_BLTString  -  Blit a null-terminated ASCII string (white)
;
; On entry: a0 = null-terminated string, a1 = screen byte address (plane 0 top).
; Destroys: d2, a0 (a1 modified: points past last character on return).
;==============================================================================

CHAR_BLTString:
    PUSHM       d2/a0
.loop
    move.b      (a0)+,d2
    beq         .done
    bsr         CHAR_BLTOneChar
    bra         .loop
.done
    POPM        d2/a0
    rts


;==============================================================================
; CHAR_BLTNum3  -  Format a word 0-999 as 3 decimal digits and blit (white)
;
; On entry: d0.w = value (0-999), a1 = screen address.
; On return: a1 advanced by 3 bytes (3 characters).
; Destroys: d0-d4.
;==============================================================================

CHAR_BLTNum3:
    PUSHM       d0-d4

    move.w      d0,d1

    ; Hundreds digit
    moveq       #0,d2
.h  cmp.w       #100,d1
    blt         .hd
    sub.w       #100,d1
    addq.w      #1,d2
    bra         .h
.hd add.b       #'0',d2
    bsr         CHAR_BLTOneChar

    ; Tens digit
    moveq       #0,d2
.t  cmp.w       #10,d1
    blt         .td
    sub.w       #10,d1
    addq.w      #1,d2
    bra         .t
.td add.b       #'0',d2
    bsr         CHAR_BLTOneChar

    ; Units digit
    move.w      d1,d2
    add.b       #'0',d2
    bsr         CHAR_BLTOneChar

    POPM        d0-d4
    rts


;==============================================================================
; CHAR_DrawBlockChar  -  Write one raw fill byte to planes 3+4 of a char cell
;
; Used for the solid block cursor: d2=$FF paints a green block (colour 24),
; d2=$00 erases.  Bypasses the font entirely.
;
; On entry: d2.b = byte to write to every plane row; a1 = screen byte address.
; On return: a1 advanced by 1 byte (next character column).
; Destroys: d4, a2 (saved/restored).
;==============================================================================

CHAR_DrawBlockChar:
    PUSHM       d4/a2
    move.l      a1,a2
    moveq       #7,d4
.dbc_row
    clr.b       0(a2)                  ; plane 0 = 0 (erase any underlying char data)
    clr.b       CHAR_PLANE1(a2)        ; plane 1 = 0
    clr.b       CHAR_PLANE2(a2)        ; plane 2 = 0
    move.b      d2,CHAR_PLANE3(a2)     ; plane 3 = cursor byte ($FF on, $00 off)
    move.b      d2,CHAR_PLANE4(a2)     ; plane 4
    add.w       #LOADING_ROW_BYTES,a2
    dbra        d4,.dbc_row
    addq.l      #1,a1
    POPM        d4/a2
    rts


;==============================================================================
; CHAR_BLTStringGreen / Yellow / Red  -  Null-terminated string blitters
;
; Like CHAR_BLTString but call the coloured single-char routines.
; a1 advances past each character written; a0 restored on return.
;==============================================================================

CHAR_BLTStringGreen:
    PUSHM       d2/a0
.gsl
    move.b      (a0)+,d2
    beq         .gsd
    bsr         CHAR_BLTGreenChar
    bra         .gsl
.gsd
    POPM        d2/a0
    rts

CHAR_BLTStringYellow:
    PUSHM       d2/a0
.ysl
    move.b      (a0)+,d2
    beq         .ysd
    bsr         CHAR_BLTYellowChar
    bra         .ysl
.ysd
    POPM        d2/a0
    rts

CHAR_BLTStringRed:
    PUSHM       d2/a0
.rsl
    move.b      (a0)+,d2
    beq         .rsd
    bsr         CHAR_BLTRedChar
    bra         .rsl
.rsd
    POPM        d2/a0
    rts

CHAR_BLTStringHud:
    PUSHM       d2/a0
.hsl
    move.b      (a0)+,d2
    beq         .hsd
    bsr         CHAR_BLTHudChar
    bra         .hsl
.hsd
    POPM        d2/a0
    rts
