; AUTO-GENERATED by assets/font/generate_michroma_font.py - DO NOT HAND-EDIT.
; Source: assets/font/Michroma-Regular.ttf (SIL OFL 1.1, see Michroma-OFL.txt).
;
; Proportional hero-text font for placard/warning screens (e.g. the PURGE
; flash effect) at 336-wide canvases - see bigfont.asm for the blit routines
; that consume these tables.  Charset: A-Z, 0-9, space (37 glyphs).
;
; MichromaFont       - glyph bitmaps, MICHROMA_H rows each, concatenated;
;                      1 bitplane, MSB = leftmost pixel.
; MichromaOffsets    - byte offset of each glyph within MichromaFont (word).
; MichromaWidths     - byte width (bytes/row) of each glyph (word).
; MichromaCharMap    - 256 bytes, ASCII code -> glyph index (space if unmapped).

MICHROMA_H      equ     49
MICHROMA_GLYPHS equ     37

MichromaFont:
    incbin  'assets/font/michroma_font.bin'
    even

MichromaOffsets:
    dc.w    0,392,784,1176,1568,1911,2205,2597
    dc.w    2989,3087,3381,3724,4018,4508,4900,5292
    dc.w    5635,6027,6419,6811,7154,7546,7889,8477
    dc.w    8869,9261,9604,9947,10290,10633,10976,11319
    dc.w    11662,12005,12348,12691,13034

MichromaWidths:
    dc.w    8,8,8,8,7,6,8,8
    dc.w    2,6,7,6,10,8,8,7
    dc.w    8,8,8,7,8,7,12,8
    dc.w    8,7,7,7,7,7,7,7
    dc.w    7,7,7,7,10

MichromaCharMap:
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    26,27,28,29,30,31,32,33,34,35,36,36,36,36,36,36
    dc.b    36,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
    dc.b    15,16,17,18,19,20,21,22,23,24,25,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    dc.b    36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
    even

